//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Scripts/Input/UI_Input_Base.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Input/UI_Input_Base.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @UI_Input_Base: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @UI_Input_Base()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""UI_Input_Base"",
    ""maps"": [
        {
            ""name"": ""UI Primer Plano"",
            ""id"": ""791898f7-b8bf-4f77-8afe-3d12703fefa1"",
            ""actions"": [
                {
                    ""name"": ""Misiones"",
                    ""type"": ""Button"",
                    ""id"": ""aa246d3a-4a55-4576-8c9e-029e377d1ac3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6ae46c2d-46a7-462b-aae3-8829c66d3da4"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Misiones"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UI Primer Plano
        m_UIPrimerPlano = asset.FindActionMap("UI Primer Plano", throwIfNotFound: true);
        m_UIPrimerPlano_Misiones = m_UIPrimerPlano.FindAction("Misiones", throwIfNotFound: true);
    }

    ~@UI_Input_Base()
    {
        UnityEngine.Debug.Assert(!m_UIPrimerPlano.enabled, "This will cause a leak and performance issues, UI_Input_Base.UIPrimerPlano.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI Primer Plano
    private readonly InputActionMap m_UIPrimerPlano;
    private List<IUIPrimerPlanoActions> m_UIPrimerPlanoActionsCallbackInterfaces = new List<IUIPrimerPlanoActions>();
    private readonly InputAction m_UIPrimerPlano_Misiones;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI Primer Plano".
    /// </summary>
    public struct UIPrimerPlanoActions
    {
        private @UI_Input_Base m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIPrimerPlanoActions(@UI_Input_Base wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UIPrimerPlano/Misiones".
        /// </summary>
        public InputAction @Misiones => m_Wrapper.m_UIPrimerPlano_Misiones;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UIPrimerPlano; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIPrimerPlanoActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIPrimerPlanoActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIPrimerPlanoActions" />
        public void AddCallbacks(IUIPrimerPlanoActions instance)
        {
            if (instance == null || m_Wrapper.m_UIPrimerPlanoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIPrimerPlanoActionsCallbackInterfaces.Add(instance);
            @Misiones.started += instance.OnMisiones;
            @Misiones.performed += instance.OnMisiones;
            @Misiones.canceled += instance.OnMisiones;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIPrimerPlanoActions" />
        private void UnregisterCallbacks(IUIPrimerPlanoActions instance)
        {
            @Misiones.started -= instance.OnMisiones;
            @Misiones.performed -= instance.OnMisiones;
            @Misiones.canceled -= instance.OnMisiones;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIPrimerPlanoActions.UnregisterCallbacks(IUIPrimerPlanoActions)" />.
        /// </summary>
        /// <seealso cref="UIPrimerPlanoActions.UnregisterCallbacks(IUIPrimerPlanoActions)" />
        public void RemoveCallbacks(IUIPrimerPlanoActions instance)
        {
            if (m_Wrapper.m_UIPrimerPlanoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIPrimerPlanoActions.AddCallbacks(IUIPrimerPlanoActions)" />
        /// <seealso cref="UIPrimerPlanoActions.RemoveCallbacks(IUIPrimerPlanoActions)" />
        /// <seealso cref="UIPrimerPlanoActions.UnregisterCallbacks(IUIPrimerPlanoActions)" />
        public void SetCallbacks(IUIPrimerPlanoActions instance)
        {
            foreach (var item in m_Wrapper.m_UIPrimerPlanoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIPrimerPlanoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIPrimerPlanoActions" /> instance referencing this action map.
    /// </summary>
    public UIPrimerPlanoActions @UIPrimerPlano => new UIPrimerPlanoActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI Primer Plano" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIPrimerPlanoActions.AddCallbacks(IUIPrimerPlanoActions)" />
    /// <seealso cref="UIPrimerPlanoActions.RemoveCallbacks(IUIPrimerPlanoActions)" />
    public interface IUIPrimerPlanoActions
    {
        /// <summary>
        /// Method invoked when associated input action "Misiones" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMisiones(InputAction.CallbackContext context);
    }
}
